<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\District;
use Illuminate\Database\Seeder;

class DistrictSeeder extends Seeder
{
    /**
     * 依縣市（zh-TW）分組的行政區。值為 zh-TW => en，採用內政部的「國際慣用名」
     * 欄位（Tamsui、Lukang 等）。
     *
     * @var array<string, array<string, string>>
     */
    public const DISTRICTS = [
        '臺北市' => [
            '松山區' => 'Songshan District',
            '信義區' => 'Xinyi District',
            '大安區' => "Da'an District",
            '中山區' => 'Zhongshan District',
            '中正區' => 'Zhongzheng District',
            '大同區' => 'Datong District',
            '萬華區' => 'Wanhua District',
            '文山區' => 'Wenshan District',
            '南港區' => 'Nangang District',
            '內湖區' => 'Neihu District',
            '士林區' => 'Shilin District',
            '北投區' => 'Beitou District',
        ],
        '新北市' => [
            '板橋區' => 'Banqiao District',
            '三重區' => 'Sanchong District',
            '中和區' => 'Zhonghe District',
            '永和區' => 'Yonghe District',
            '新莊區' => 'Xinzhuang District',
            '新店區' => 'Xindian District',
            '土城區' => 'Tucheng District',
            '蘆洲區' => 'Luzhou District',
            '汐止區' => 'Xizhi District',
            '樹林區' => 'Shulin District',
            '淡水區' => 'Tamsui District',
            '鶯歌區' => 'Yingge District',
            '三峽區' => 'Sanxia District',
            '瑞芳區' => 'Ruifang District',
            '五股區' => 'Wugu District',
            '泰山區' => 'Taishan District',
            '林口區' => 'Linkou District',
            '深坑區' => 'Shenkeng District',
            '石碇區' => 'Shiding District',
            '坪林區' => 'Pinglin District',
            '三芝區' => 'Sanzhi District',
            '石門區' => 'Shimen District',
            '八里區' => 'Bali District',
            '平溪區' => 'Pingxi District',
            '雙溪區' => 'Shuangxi District',
            '貢寮區' => 'Gongliao District',
            '金山區' => 'Jinshan District',
            '萬里區' => 'Wanli District',
            '烏來區' => 'Wulai District',
        ],
        '桃園市' => [
            '桃園區' => 'Taoyuan District',
            '中壢區' => 'Zhongli District',
            '大溪區' => 'Daxi District',
            '楊梅區' => 'Yangmei District',
            '蘆竹區' => 'Luzhu District',
            '大園區' => 'Dayuan District',
            '龜山區' => 'Guishan District',
            '八德區' => 'Bade District',
            '龍潭區' => 'Longtan District',
            '平鎮區' => 'Pingzhen District',
            '新屋區' => 'Xinwu District',
            '觀音區' => 'Guanyin District',
            '復興區' => 'Fuxing District',
        ],
        '臺中市' => [
            '中區' => 'Central District',
            '東區' => 'East District',
            '南區' => 'South District',
            '西區' => 'West District',
            '北區' => 'North District',
            '西屯區' => 'Xitun District',
            '南屯區' => 'Nantun District',
            '北屯區' => 'Beitun District',
            '豐原區' => 'Fengyuan District',
            '東勢區' => 'Dongshi District',
            '大甲區' => 'Dajia District',
            '清水區' => 'Qingshui District',
            '沙鹿區' => 'Shalu District',
            '梧棲區' => 'Wuqi District',
            '后里區' => 'Houli District',
            '神岡區' => 'Shengang District',
            '潭子區' => 'Tanzi District',
            '大雅區' => 'Daya District',
            '新社區' => 'Xinshe District',
            '石岡區' => 'Shigang District',
            '外埔區' => 'Waipu District',
            '大安區' => "Da'an District",
            '烏日區' => 'Wuri District',
            '大肚區' => 'Dadu District',
            '龍井區' => 'Longjing District',
            '霧峰區' => 'Wufeng District',
            '太平區' => 'Taiping District',
            '大里區' => 'Dali District',
            '和平區' => 'Heping District',
        ],
        '臺南市' => [
            '新營區' => 'Xinying District',
            '鹽水區' => 'Yanshui District',
            '白河區' => 'Baihe District',
            '柳營區' => 'Liuying District',
            '後壁區' => 'Houbi District',
            '東山區' => 'Dongshan District',
            '麻豆區' => 'Madou District',
            '下營區' => 'Xiaying District',
            '六甲區' => 'Liujia District',
            '官田區' => 'Guantian District',
            '大內區' => 'Danei District',
            '佳里區' => 'Jiali District',
            '學甲區' => 'Xuejia District',
            '西港區' => 'Xigang District',
            '七股區' => 'Qigu District',
            '將軍區' => 'Jiangjun District',
            '北門區' => 'Beimen District',
            '新化區' => 'Xinhua District',
            '善化區' => 'Shanhua District',
            '新市區' => 'Xinshi District',
            '安定區' => 'Anding District',
            '山上區' => 'Shanshang District',
            '玉井區' => 'Yujing District',
            '楠西區' => 'Nanxi District',
            '南化區' => 'Nanhua District',
            '左鎮區' => 'Zuozhen District',
            '仁德區' => 'Rende District',
            '歸仁區' => 'Guiren District',
            '關廟區' => 'Guanmiao District',
            '龍崎區' => 'Longqi District',
            '永康區' => 'Yongkang District',
            '東區' => 'East District',
            '南區' => 'South District',
            '北區' => 'North District',
            '安南區' => 'Annan District',
            '安平區' => 'Anping District',
            '中西區' => 'West Central District',
        ],
        '高雄市' => [
            '鹽埕區' => 'Yancheng District',
            '鼓山區' => 'Gushan District',
            '左營區' => 'Zuoying District',
            '楠梓區' => 'Nanzi District',
            '三民區' => 'Sanmin District',
            '新興區' => 'Xinxing District',
            '前金區' => 'Qianjin District',
            '苓雅區' => 'Lingya District',
            '前鎮區' => 'Qianzhen District',
            '旗津區' => 'Qijin District',
            '小港區' => 'Xiaogang District',
            '鳳山區' => 'Fengshan District',
            '林園區' => 'Linyuan District',
            '大寮區' => 'Daliao District',
            '大樹區' => 'Dashu District',
            '大社區' => 'Dashe District',
            '仁武區' => 'Renwu District',
            '鳥松區' => 'Niaosong District',
            '岡山區' => 'Gangshan District',
            '橋頭區' => 'Qiaotou District',
            '燕巢區' => 'Yanchao District',
            '田寮區' => 'Tianliao District',
            '阿蓮區' => 'Alian District',
            '路竹區' => 'Luzhu District',
            '湖內區' => 'Hunei District',
            '茄萣區' => 'Qieding District',
            '永安區' => "Yong'an District",
            '彌陀區' => 'Mituo District',
            '梓官區' => 'Ziguan District',
            '旗山區' => 'Qishan District',
            '美濃區' => 'Meinong District',
            '六龜區' => 'Liugui District',
            '甲仙區' => 'Jiaxian District',
            '杉林區' => 'Shanlin District',
            '內門區' => 'Neimen District',
            '茂林區' => 'Maolin District',
            '桃源區' => 'Taoyuan District',
            '那瑪夏區' => 'Namaxia District',
        ],
        '基隆市' => [
            '中正區' => 'Zhongzheng District',
            '七堵區' => 'Qidu District',
            '暖暖區' => 'Nuannuan District',
            '仁愛區' => "Ren'ai District",
            '中山區' => 'Zhongshan District',
            '安樂區' => 'Anle District',
            '信義區' => 'Xinyi District',
        ],
        '新竹市' => [
            '東區' => 'East District',
            '北區' => 'North District',
            '香山區' => 'Xiangshan District',
        ],
        '嘉義市' => [
            '東區' => 'East District',
            '西區' => 'West District',
        ],
        '新竹縣' => [
            '竹北市' => 'Zhubei City',
            '竹東鎮' => 'Zhudong Township',
            '新埔鎮' => 'Xinpu Township',
            '湖口鄉' => 'Hukou Township',
            '新豐鄉' => 'Xinfeng Township',
            '芎林鄉' => 'Qionglin Township',
            '橫山鄉' => 'Hengshan Township',
            '北埔鄉' => 'Beipu Township',
            '寶山鄉' => 'Baoshan Township',
            '關西鎮' => 'Guanxi Township',
            '峨眉鄉' => 'Emei Township',
            '尖石鄉' => 'Jianshi Township',
            '五峰鄉' => 'Wufeng Township',
        ],
        '苗栗縣' => [
            '苗栗市' => 'Miaoli City',
            '苑裡鎮' => 'Yuanli Township',
            '通霄鎮' => 'Tongxiao Township',
            '竹南鎮' => 'Zhunan Township',
            '頭份市' => 'Toufen City',
            '後龍鎮' => 'Houlong Township',
            '卓蘭鎮' => 'Zhuolan Township',
            '大湖鄉' => 'Dahu Township',
            '公館鄉' => 'Gongguan Township',
            '銅鑼鄉' => 'Tongluo Township',
            '南庄鄉' => 'Nanzhuang Township',
            '頭屋鄉' => 'Touwu Township',
            '三義鄉' => 'Sanyi Township',
            '西湖鄉' => 'Xihu Township',
            '造橋鄉' => 'Zaoqiao Township',
            '三灣鄉' => 'Sanwan Township',
            '獅潭鄉' => 'Shitan Township',
            '泰安鄉' => "Tai'an Township",
        ],
        '彰化縣' => [
            '彰化市' => 'Changhua City',
            '鹿港鎮' => 'Lukang Township',
            '和美鎮' => 'Hemei Township',
            '線西鄉' => 'Xianxi Township',
            '伸港鄉' => 'Shengang Township',
            '福興鄉' => 'Fuxing Township',
            '秀水鄉' => 'Xiushui Township',
            '花壇鄉' => 'Huatan Township',
            '芬園鄉' => 'Fenyuan Township',
            '員林市' => 'Yuanlin City',
            '溪湖鎮' => 'Xihu Township',
            '田中鎮' => 'Tianzhong Township',
            '大村鄉' => 'Dacun Township',
            '埔鹽鄉' => 'Puyan Township',
            '埔心鄉' => 'Puxin Township',
            '永靖鄉' => 'Yongjing Township',
            '社頭鄉' => 'Shetou Township',
            '二水鄉' => 'Ershui Township',
            '北斗鎮' => 'Beidou Township',
            '二林鎮' => 'Erlin Township',
            '田尾鄉' => 'Tianwei Township',
            '埤頭鄉' => 'Pitou Township',
            '芳苑鄉' => 'Fangyuan Township',
            '大城鄉' => 'Dacheng Township',
            '竹塘鄉' => 'Zhutang Township',
            '溪州鄉' => 'Xizhou Township',
        ],
        '南投縣' => [
            '南投市' => 'Nantou City',
            '埔里鎮' => 'Puli Township',
            '草屯鎮' => 'Caotun Township',
            '竹山鎮' => 'Zhushan Township',
            '集集鎮' => 'Jiji Township',
            '名間鄉' => 'Mingjian Township',
            '鹿谷鄉' => 'Lugu Township',
            '中寮鄉' => 'Zhongliao Township',
            '魚池鄉' => 'Yuchi Township',
            '國姓鄉' => 'Guoxing Township',
            '水里鄉' => 'Shuili Township',
            '信義鄉' => 'Xinyi Township',
            '仁愛鄉' => "Ren'ai Township",
        ],
        '雲林縣' => [
            '斗六市' => 'Douliu City',
            '斗南鎮' => 'Dounan Township',
            '虎尾鎮' => 'Huwei Township',
            '西螺鎮' => 'Xiluo Township',
            '土庫鎮' => 'Tuku Township',
            '北港鎮' => 'Beigang Township',
            '古坑鄉' => 'Gukeng Township',
            '大埤鄉' => 'Dapi Township',
            '莿桐鄉' => 'Citong Township',
            '林內鄉' => 'Linnei Township',
            '二崙鄉' => 'Erlun Township',
            '崙背鄉' => 'Lunbei Township',
            '麥寮鄉' => 'Mailiao Township',
            '東勢鄉' => 'Dongshi Township',
            '褒忠鄉' => 'Baozhong Township',
            '臺西鄉' => 'Taixi Township',
            '元長鄉' => 'Yuanzhang Township',
            '四湖鄉' => 'Sihu Township',
            '口湖鄉' => 'Kouhu Township',
            '水林鄉' => 'Shuilin Township',
        ],
        '嘉義縣' => [
            '太保市' => 'Taibao City',
            '朴子市' => 'Puzi City',
            '布袋鎮' => 'Budai Township',
            '大林鎮' => 'Dalin Township',
            '民雄鄉' => 'Minxiong Township',
            '溪口鄉' => 'Xikou Township',
            '新港鄉' => 'Xingang Township',
            '六腳鄉' => 'Liujiao Township',
            '東石鄉' => 'Dongshi Township',
            '義竹鄉' => 'Yizhu Township',
            '鹿草鄉' => 'Lucao Township',
            '水上鄉' => 'Shuishang Township',
            '中埔鄉' => 'Zhongpu Township',
            '竹崎鄉' => 'Zhuqi Township',
            '梅山鄉' => 'Meishan Township',
            '番路鄉' => 'Fanlu Township',
            '大埔鄉' => 'Dapu Township',
            '阿里山鄉' => 'Alishan Township',
        ],
        '屏東縣' => [
            '屏東市' => 'Pingtung City',
            '潮州鎮' => 'Chaozhou Township',
            '東港鎮' => 'Donggang Township',
            '恆春鎮' => 'Hengchun Township',
            '萬丹鄉' => 'Wandan Township',
            '長治鄉' => 'Changzhi Township',
            '麟洛鄉' => 'Linluo Township',
            '九如鄉' => 'Jiuru Township',
            '里港鄉' => 'Ligang Township',
            '鹽埔鄉' => 'Yanpu Township',
            '高樹鄉' => 'Gaoshu Township',
            '萬巒鄉' => 'Wanluan Township',
            '內埔鄉' => 'Neipu Township',
            '竹田鄉' => 'Zhutian Township',
            '新埤鄉' => 'Xinpi Township',
            '枋寮鄉' => 'Fangliao Township',
            '新園鄉' => 'Xinyuan Township',
            '崁頂鄉' => 'Kanding Township',
            '林邊鄉' => 'Linbian Township',
            '南州鄉' => 'Nanzhou Township',
            '佳冬鄉' => 'Jiadong Township',
            '琉球鄉' => 'Liuqiu Township',
            '車城鄉' => 'Checheng Township',
            '滿州鄉' => 'Manzhou Township',
            '枋山鄉' => 'Fangshan Township',
            '三地門鄉' => 'Sandimen Township',
            '霧臺鄉' => 'Wutai Township',
            '瑪家鄉' => 'Majia Township',
            '泰武鄉' => 'Taiwu Township',
            '來義鄉' => 'Laiyi Township',
            '春日鄉' => 'Chunri Township',
            '獅子鄉' => 'Shizi Township',
            '牡丹鄉' => 'Mudan Township',
        ],
        '宜蘭縣' => [
            '宜蘭市' => 'Yilan City',
            '羅東鎮' => 'Luodong Township',
            '蘇澳鎮' => "Su'ao Township",
            '頭城鎮' => 'Toucheng Township',
            '礁溪鄉' => 'Jiaoxi Township',
            '壯圍鄉' => 'Zhuangwei Township',
            '員山鄉' => 'Yuanshan Township',
            '冬山鄉' => 'Dongshan Township',
            '五結鄉' => 'Wujie Township',
            '三星鄉' => 'Sanxing Township',
            '大同鄉' => 'Datong Township',
            '南澳鄉' => "Nan'ao Township",
        ],
        '花蓮縣' => [
            '花蓮市' => 'Hualien City',
            '鳳林鎮' => 'Fenglin Township',
            '玉里鎮' => 'Yuli Township',
            '新城鄉' => 'Xincheng Township',
            '吉安鄉' => "Ji'an Township",
            '壽豐鄉' => 'Shoufeng Township',
            '光復鄉' => 'Guangfu Township',
            '豐濱鄉' => 'Fengbin Township',
            '瑞穗鄉' => 'Ruisui Township',
            '富里鄉' => 'Fuli Township',
            '秀林鄉' => 'Xiulin Township',
            '萬榮鄉' => 'Wanrong Township',
            '卓溪鄉' => 'Zhuoxi Township',
        ],
        '臺東縣' => [
            '臺東市' => 'Taitung City',
            '成功鎮' => 'Chenggong Township',
            '關山鎮' => 'Guanshan Township',
            '卑南鄉' => 'Beinan Township',
            '鹿野鄉' => 'Luye Township',
            '池上鄉' => 'Chishang Township',
            '東河鄉' => 'Donghe Township',
            '長濱鄉' => 'Changbin Township',
            '太麻里鄉' => 'Taimali Township',
            '大武鄉' => 'Dawu Township',
            '綠島鄉' => 'Lüdao Township',
            '海端鄉' => 'Haiduan Township',
            '延平鄉' => 'Yanping Township',
            '金峰鄉' => 'Jinfeng Township',
            '達仁鄉' => 'Daren Township',
            '蘭嶼鄉' => 'Lanyu Township',
        ],
        '澎湖縣' => [
            '馬公市' => 'Magong City',
            '湖西鄉' => 'Huxi Township',
            '白沙鄉' => 'Baisha Township',
            '西嶼鄉' => 'Xiyu Township',
            '望安鄉' => "Wang'an Township",
            '七美鄉' => 'Qimei Township',
        ],
        '金門縣' => [
            '金城鎮' => 'Jincheng Township',
            '金湖鎮' => 'Jinhu Township',
            '金沙鎮' => 'Jinsha Township',
            '金寧鄉' => 'Jinning Township',
            '烈嶼鄉' => 'Lieyu Township',
            '烏坵鄉' => 'Wuqiu Township',
        ],
        '連江縣' => [
            '南竿鄉' => 'Nangan Township',
            '北竿鄉' => 'Beigan Township',
            '莒光鄉' => 'Juguang Township',
            '東引鄉' => 'Dongyin Township',
        ],
    ];

    /**
     * 執行資料填充。
     *
     * 以「縣市 + 中文名稱」當作識別鍵，重複執行只會更新既有資料，不會產生重複的行政區。
     */
    public function run(): void
    {
        $cityIds = City::all()->mapWithKeys(fn(City $city) => [
            $city->getTranslation('name', 'zh-TW') => $city->id,
        ]);

        $existing = District::all()
            ->groupBy('city_id')
            ->map(fn($districts) => $districts->keyBy(
                fn(District $district) => $district->getTranslation('name', 'zh-TW')
            ));

        foreach (self::DISTRICTS as $cityZh => $districts) {
            $cityId = $cityIds[$cityZh];

            foreach ($districts as $zh => $en) {
                $district = $existing->get($cityId)?->get($zh) ?? new District(['city_id' => $cityId]);
                $district->setTranslations('name', ['zh-TW' => $zh, 'en' => $en]);
                $district->save();
            }
        }
    }
}
